apiVersion: apps/v1
kind: Deployment
metadata:
  name: RoomManagement
  labels:
    app: RoomManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RoomManagement
  template:
    metadata:
      labels:
        app: RoomManagement
    spec:
      containers:
        - name: RoomManagement
          image: username/RoomManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5